---
# copy docker file to all hosts
- hosts: all
  become: yes
  tasks:

  - name: Creates directory dockers
    file:
      path: /opt/dockers/nginx
      state: directory
      #owner: root
      #group: root
      mode: 0775
    tags: copy-dockerfile

  - name: copy docker file all host c7 vs u1604.
    copy:
      src: /home/quangch/Desktop/SystemAll/TAI LIEU DEPLOYED HE THONG/K8S/DockerFolder/nginx/
      dest: /opt/dockers/nginx
      mode: 0774
    tags: copy-dockerfile


  - name: copy file passdocker.txt
    template:
      src: "{{ item }}"
      dest: /opt/dockers
      mode: 0775
    with_items:
      - passdocker.txt
    tags: copy-passdocker

  - name: shell command docker login
    shell: cat /opt/dockers/passdocker.txt | docker login --username=quanghong10 --password-stdin
    args:
      chdir: /opt/dockers
    tags: copy-passdocker

  - name: restart docker
    become: true
    service:
      name: docker
      state: restarted
    tags: restart-docker


  - name: Copy firewall script into place.
    template:
      src: firewall.bash
      dest: /etc/firewall.bash
      owner: root
      group: root
      mode: 0744
    tags: copy-firewall.bash

  - name: restart firewall
    service: name=firewall state=restarted
    tags: copy-firewall.bash
  








