---
# copy telegraf.conf to all hosts
- hosts: u16-server
  become: yes
  tasks:
  - name: copy telegraf conf all host
    template:
      src: telegraf.conf.j2
      dest: /etc/telegraf/telegraf.conf
      force: yes
      backup: yes
      owner: telegraf
      group: telegraf
      mode: 0744
    tags: telegraf-copy

  - name: copy config to folder telegraf.d
    template:
      src: "{{ item }}"
      dest: /etc/telegraf/telegraf.d
      force: yes
      backup: yes
      owner: telegraf
      group: telegraf
      mode: 0744
    with_items:
#      - telegraf_ping.conf
#      - telegraf_snmp_bw.conf
#      - telegraf_snmp_sw_3750_2960.conf
#      - telegraf_window_server.conf
    tags: telegraf-copy



  - name: Restarted telegraf service
    service:
       name: telegraf
       state: restarted
    tags: telegraf-copy


