---
# install docker on ubuntu 16.04


- name: purge old docker packages
  apt:
    name:
      - docker
      - docker-common
      - container-selinux
      - docker-selinux
      - docker-engine
    state: absent

- name: Install required packages
  become: yes
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common


- name: Add docker's official GPG key to apt
  become: true
  apt_key:
    url: "{{ docker_key_url }}"
    state: present


- name: Add Docker's apt repository
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present


- name: Install docker CE
  become: true
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - "docker-ce"
    - "docker-ce-cli"
    - "containerd.io"
  notify: restart docker


- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: true


- name: Add user to docker group
  become: true
  user:
    name: "{{ item }}"
    groups: "docker"
  with_items: "{{ docker_users }}"

- name: Install latest version of docker-compose
  become: true
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: "/usr/local/bin/docker-compose"
    owner: "root"
    mode: "+x"

- name: shell command docker run hello-world
  shell: docker run hello-world
  tags: run-docker-hello






              
           
